CREATE SCHEMA "FLIGHTS" AUTHORIZATION postgres;
-- Aeropuertos (AIRPORTS)
CREATE TABLE "FLIGHTS"."AIRPORTS" (
  "IATA" character(3),
  "CITY" character(10)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE "FLIGHTS"."AIRPORTS"
  OWNER TO postgres;

 -- Table: "FLIGHTS"."AIR_LINES_PRICE_INFANT"
-- DROP TABLE "FLIGHTS"."AIR_LINES_PRICE_INFANT";
CREATE TABLE "FLIGHTS"."AIR_LINES_PRICE_INFANT"
(
  "IATA_CODE" character(2),
  "NAME" character(50),
  "PRICE" double precision
)
WITH (
  OIDS=FALSE
);
ALTER TABLE "FLIGHTS"."AIR_LINES_PRICE_INFANT"
  OWNER TO postgres;
  
-- Table: "FLIGHTS"."FLIGHTS"
-- DROP TABLE "FLIGHTS"."FLIGHTS";
CREATE TABLE "FLIGHTS"."FLIGHTS"
(
  "ORIGIN" character(3),
  "DESTINATION" character(3),
  "AIRLINE" character(6),
  "BASE_PRICE" double precision
)
WITH (
  OIDS=FALSE
);
ALTER TABLE "FLIGHTS"."FLIGHTS"
  OWNER TO postgres;
GRANT ALL ON TABLE "FLIGHTS"."FLIGHTS" TO postgres;
GRANT ALL ON TABLE "FLIGHTS"."FLIGHTS" TO public;

-- Table: "FLIGHTS"."PASSENGER_TYPE"
-- DROP TABLE "FLIGHTS"."PASSENGER_TYPE";
CREATE TABLE "FLIGHTS"."PASSENGER_TYPE"
(
  "TIPO" character(1),
  "PRICE" double precision
)
WITH (
  OIDS=FALSE
);
ALTER TABLE "FLIGHTS"."PASSENGER_TYPE"
  OWNER TO postgres;
GRANT ALL ON TABLE "FLIGHTS"."PASSENGER_TYPE" TO postgres;

-- Index: "FLIGHTS".tipo
-- DROP INDEX "FLIGHTS".tipo;
CREATE UNIQUE INDEX tipo
  ON "FLIGHTS"."PASSENGER_TYPE"
  USING btree
  ("TIPO" COLLATE pg_catalog."default");